export const SliderData = [
    {
      image:
      "https://i.postimg.cc/VkgX3M3C/gracepic1.jpg"
    },
    {
      image:
      "https://i.postimg.cc/66n1pmcf/marura.jpg"
    },
    {
      image:
      "https://i.postimg.cc/KYn7Jwmm/Whats-App-Image-2023-01-04-at-02-05-38.jpg"
    },
    {
      image:
      "https://i.postimg.cc/DfgSBFsC/Whats-App-Image-2023-01-06-at-04-36-06.jpg"
    },
    {
      image:
      "https://i.postimg.cc/KYn7Jwmm/Whats-App-Image-2023-01-04-at-02-05-38.jpg"
    }
  ];